# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CdCli < Formula
  desc ""
  homepage ""
  version "0.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/giantswarm/cloud-director-cli/releases/download/v0.0.6/cd-cli_darwin-arm64"
      sha256 "5cc4e665ae9e201f9b318e17074c827d3b88d1e5661fcd01f96a45ec86b44c0e"

      def install
        bin.install stable.url.split("/")[-1] => "cd-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/giantswarm/cloud-director-cli/releases/download/v0.0.6/cd-cli_darwin-amd64"
      sha256 "531f3d4c811b31bea33ab2d74831ee81bfd53246aa0018a4d8b45ca2b51a49aa"

      def install
        bin.install stable.url.split("/")[-1] => "cd-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/giantswarm/cloud-director-cli/releases/download/v0.0.6/cd-cli_linux-arm64"
      sha256 "6e28aded9e31de499129e8c2fb352ddbe258535740b70dfc6601fa95443acf2d"

      def install
        bin.install stable.url.split("/")[-1] => "cd-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/giantswarm/cloud-director-cli/releases/download/v0.0.6/cd-cli_linux-amd64"
      sha256 "9a088e67ac4f2d656da70e84eac27fce216bd9357f9cf65a39fd64b6d9981fd4"

      def install
        bin.install stable.url.split("/")[-1] => "cd-cli"
      end
    end
  end
end
