# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CdCli < Formula
  desc ""
  homepage ""
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/giantswarm/cloud-director-cli/releases/download/v0.1.0/cd-cli_darwin-arm64"
      sha256 "5ec4eeff01325f0f8c3ddbacfab080d3806c831c0630b8f190e1c3c83bcb7500"

      def install
        bin.install stable.url.split("/")[-1] => "cd-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/giantswarm/cloud-director-cli/releases/download/v0.1.0/cd-cli_darwin-amd64"
      sha256 "1a9582f91b8a99ad54f5daecf5ae5e5b9794396d638dd0dc001db783551ae46d"

      def install
        bin.install stable.url.split("/")[-1] => "cd-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/giantswarm/cloud-director-cli/releases/download/v0.1.0/cd-cli_linux-amd64"
      sha256 "847eb9540810ffa04b70651a95478fe2c493950691965c0c30807199801a42d4"

      def install
        bin.install stable.url.split("/")[-1] => "cd-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/giantswarm/cloud-director-cli/releases/download/v0.1.0/cd-cli_linux-arm64"
      sha256 "d42e6c846ab0107c86a6b71d9afa8bab3eed91c5a96885907c426d7ca9fad57d"

      def install
        bin.install stable.url.split("/")[-1] => "cd-cli"
      end
    end
  end
end
